#!/bin/bash
#
#yl2
#
echo "Veljo Saago" #väljastab nime uuele reale
echo "ISP118" #väljastab õppegrupi uuele reale
echo "Antud aine tundub erakordselt huvitav" #väljastab kirjelduse uuele reale
echo "Praegune mulje on tore, edasijõudmine pole väga raske" #väljastab kirjelduse ja läheb uuele reale 
#
#skripti lõpp
